spring:
  application:
    name: expense-tracker-backend

  datasource:
    url: jdbc:h2:mem:expense_tracker
    driver: org.h2.Driver
    username: su
    password: su@123

  h2.console.enabled: true
  h2.console.path: /h2-console
